import nmap
import requests
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from datetime import datetime

console = Console()

def search_cve(service, version):
    if not version or version.strip() == "":
        return []
    try:
        keyword = f"{service} {version}"
        url = f"https://cve.circl.lu/api/search/{keyword}"
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            data = response.json()
            return data.get("results", [])[:3]
    except:
        return []
    return []

def generate_html_report(target, scan_results, os_info):
    """Xuất báo cáo HTML chuyên nghiệp"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    rows = ""
    for port, state, service, version, danger, cves in scan_results:
        cve_html = ""
        if cves:
            cve_html = "<br>".join([f"⚠️ <b>{c.get('id','')}</b>: CVSS {c.get('cvss','N/A')}" for c in cves])
        else:
            cve_html = "✅ Không tìm thấy CVE"
        
        state_color = "#00ff00" if state == "open" else "#ff4444"
        rows += f"""
        <tr>
            <td>{port}</td>
            <td style="color:{state_color}"><b>{state.upper()}</b></td>
            <td>{service}</td>
            <td>{version}</td>
            <td>{danger}</td>
            <td>{cve_html}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <title>Security Report - {target}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ background: #0a0a0a; color: #e0e0e0; font-family: 'Courier New', monospace; padding: 30px; }}
        .header {{ background: linear-gradient(135deg, #0d1117, #1a1f2e); border: 1px solid #00d4ff; border-radius: 10px; padding: 30px; margin-bottom: 30px; }}
        .header h1 {{ color: #00d4ff; font-size: 28px; margin-bottom: 10px; }}
        .header p {{ color: #888; }}
        .badge {{ display: inline-block; background: #00d4ff22; border: 1px solid #00d4ff; color: #00d4ff; padding: 4px 12px; border-radius: 20px; font-size: 12px; margin: 4px; }}
        .section {{ background: #0d1117; border: 1px solid #2a2a2a; border-radius: 10px; padding: 20px; margin-bottom: 20px; }}
        .section h2 {{ color: #00d4ff; margin-bottom: 15px; font-size: 18px; }}
        table {{ width: 100%; border-collapse: collapse; }}
        th {{ background: #1a1f2e; color: #00d4ff; padding: 12px; text-align: left; border-bottom: 1px solid #00d4ff44; }}
        td {{ padding: 12px; border-bottom: 1px solid #2a2a2a; font-size: 13px; }}
        tr:hover {{ background: #1a1f2e55; }}
        .os-box {{ background: #1a1f2e; border-left: 4px solid #00d4ff; padding: 15px; border-radius: 5px; }}
        .footer {{ text-align: center; color: #444; margin-top: 30px; font-size: 12px; }}
        .risk-high {{ color: #ff4444; }}
        .risk-med {{ color: #ffaa00; }}
        .risk-low {{ color: #00ff00; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ Network Security Report</h1>
        <p>Target: <b style="color:#fff">{target}</b></p>
        <p>Thời gian scan: {timestamp}</p>
        <br>
        <span class="badge">Pentest Report</span>
        <span class="badge">v3.0</span>
        <span class="badge">Made by Quan</span>
    </div>

    <div class="section">
        <h2>🖥️ Thông tin hệ điều hành</h2>
        <div class="os-box">{os_info}</div>
    </div>

    <div class="section">
        <h2>📊 Kết quả scan Port</h2>
        <table>
            <tr>
                <th>Port</th>
                <th>Trạng thái</th>
                <th>Dịch vụ</th>
                <th>Phiên bản</th>
                <th>Mức độ nguy hiểm</th>
                <th>CVE</th>
            </tr>
            {rows}
        </table>
    </div>

    <div class="footer">
        <p>Generated by Network Security Scanner v3.0 | {timestamp}</p>
    </div>
</body>
</html>"""

    filename = f"report_{target.replace('.', '_')}_{datetime.now().strftime('%H%M%S')}.html"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)
    return filename

def scan_target(target, ports="1-1000"):
    console.print(Panel(f"[bold cyan]🔍 Đang scan: {target}\n[yellow]Ports: {ports}[/yellow]",
                        title="Network Scanner v3.0", border_style="cyan"))

    nm = nmap.PortScanner()
    
    # Scan với OS detection
    console.print("[yellow]⏳ Đang scan ports + OS...[/yellow]")
    nm.scan(target, ports, arguments="-sV -O --osscan-guess")

    # Lấy thông tin OS
    os_info = "Không xác định được OS"
    for host in nm.all_hosts():
        if "osmatch" in nm[host] and nm[host]["osmatch"]:
            best_match = nm[host]["osmatch"][0]
            os_info = f"🖥️ {best_match['name']} (Độ chính xác: {best_match['accuracy']}%)"

    # Bảng kết quả
    table = Table(title=f"📊 Kết quả: {target}", border_style="cyan")
    table.add_column("Port", style="cyan", width=8)
    table.add_column("Trạng thái", width=12)
    table.add_column("Dịch vụ", style="yellow", width=15)
    table.add_column("Phiên bản", width=25)
    table.add_column("Nguy hiểm", width=25)

    scan_results = []
    danger_ports = {
        22: "⚠️ SSH - Brute force",
        21: "🔴 FTP - Không mã hóa",
        23: "🔴 Telnet - Rất nguy hiểm",
        80: "🟡 HTTP - Không mã hóa",
        443: "🟢 HTTPS - An toàn",
        3306: "🔴 MySQL - Exposed!",
        8080: "🟡 HTTP Alternate"
    }

    for host in nm.all_hosts():
        for proto in nm[host].all_protocols():
            for port in sorted(nm[host][proto].keys()):
                state = nm[host][proto][port]["state"]
                service = nm[host][proto][port]["name"]
                version = nm[host][proto][port]["version"]
                danger = danger_ports.get(port, "🔵 Cần kiểm tra")
                
                state_display = "[bold green]● OPEN[/]" if state == "open" else "[red]● CLOSED[/]"
                table.add_row(str(port), state_display, service, version, danger)

                if state == "open":
                    cves = search_cve(service, version)
                    scan_results.append((port, state, service, version, danger, cves))

    console.print(table)
    console.print(f"\n[cyan]🖥️ OS Detection: {os_info}[/cyan]")

    # Tra CVE
    console.print("\n[bold yellow]🔎 Đang tra CVE...[/bold yellow]")
    for port, state, service, version, danger, cves in scan_results:
        if cves:
            for cve in cves:
                console.print(f"[red]⚠️  Port {port} - {cve.get('id')}: CVSS {cve.get('cvss','N/A')}[/red]")
        else:
            console.print(f"[green]✅ Port {port} ({service}): Không tìm thấy CVE[/green]")

    # Xuất báo cáo HTML
    console.print("\n[yellow]📝 Đang xuất báo cáo HTML...[/yellow]")
    filename = generate_html_report(target, scan_results, os_info)
    
    console.print(Panel(
        f"[green]✅ Scan hoàn tất!\n"
        f"[cyan]📌 Port mở: {len(scan_results)}\n"
        f"[cyan]🖥️  OS: {os_info}\n"
        f"[yellow]📄 Báo cáo: [bold]{filename}[/bold]",
        title="Tổng kết", border_style="green"
    ))

if __name__ == "__main__":
    console.print(Panel("[bold cyan]🛡️  Network Security Scanner v3.0\n[white]Made by: Quan + AI 😄",
                        border_style="cyan"))
    target = input("\nNhập IP hoặc domain cần scan: ")
    scan_target(target)
